# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'bhicks8364@gmail.com'
  config.password       = 'Hannah08'
  config.integrator_key = 'INCL-d1f22c21-e68f-4e07-b5e8-2f706d451ab6'
  config.account_id     = '1223252'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'
end

