# == Schema Information
#
# Table name: direct_deposits
#
#  id                :integer          not null, primary key
#  employee_id       :integer
#  account_number    :string
#  routing_number    :string
#  acct_confirmation :string
#  admin_id          :string
#  effective_date    :datetime
#  account_type      :string           default("Checking")
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_direct_deposits_on_employee_id  (employee_id)
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DirectDepositsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DirectDeposit. As you add validations to DirectDeposit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DirectDepositsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all direct_deposits as @direct_deposits" do
      direct_deposit = DirectDeposit.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:direct_deposits)).to eq([direct_deposit])
    end
  end

  describe "GET #show" do
    it "assigns the requested direct_deposit as @direct_deposit" do
      direct_deposit = DirectDeposit.create! valid_attributes
      get :show, {:id => direct_deposit.to_param}, valid_session
      expect(assigns(:direct_deposit)).to eq(direct_deposit)
    end
  end

  describe "GET #new" do
    it "assigns a new direct_deposit as @direct_deposit" do
      get :new, {}, valid_session
      expect(assigns(:direct_deposit)).to be_a_new(DirectDeposit)
    end
  end

  describe "GET #edit" do
    it "assigns the requested direct_deposit as @direct_deposit" do
      direct_deposit = DirectDeposit.create! valid_attributes
      get :edit, {:id => direct_deposit.to_param}, valid_session
      expect(assigns(:direct_deposit)).to eq(direct_deposit)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DirectDeposit" do
        expect {
          post :create, {:direct_deposit => valid_attributes}, valid_session
        }.to change(DirectDeposit, :count).by(1)
      end

      it "assigns a newly created direct_deposit as @direct_deposit" do
        post :create, {:direct_deposit => valid_attributes}, valid_session
        expect(assigns(:direct_deposit)).to be_a(DirectDeposit)
        expect(assigns(:direct_deposit)).to be_persisted
      end

      it "redirects to the created direct_deposit" do
        post :create, {:direct_deposit => valid_attributes}, valid_session
        expect(response).to redirect_to(DirectDeposit.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved direct_deposit as @direct_deposit" do
        post :create, {:direct_deposit => invalid_attributes}, valid_session
        expect(assigns(:direct_deposit)).to be_a_new(DirectDeposit)
      end

      it "re-renders the 'new' template" do
        post :create, {:direct_deposit => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested direct_deposit" do
        direct_deposit = DirectDeposit.create! valid_attributes
        put :update, {:id => direct_deposit.to_param, :direct_deposit => new_attributes}, valid_session
        direct_deposit.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested direct_deposit as @direct_deposit" do
        direct_deposit = DirectDeposit.create! valid_attributes
        put :update, {:id => direct_deposit.to_param, :direct_deposit => valid_attributes}, valid_session
        expect(assigns(:direct_deposit)).to eq(direct_deposit)
      end

      it "redirects to the direct_deposit" do
        direct_deposit = DirectDeposit.create! valid_attributes
        put :update, {:id => direct_deposit.to_param, :direct_deposit => valid_attributes}, valid_session
        expect(response).to redirect_to(direct_deposit)
      end
    end

    context "with invalid params" do
      it "assigns the direct_deposit as @direct_deposit" do
        direct_deposit = DirectDeposit.create! valid_attributes
        put :update, {:id => direct_deposit.to_param, :direct_deposit => invalid_attributes}, valid_session
        expect(assigns(:direct_deposit)).to eq(direct_deposit)
      end

      it "re-renders the 'edit' template" do
        direct_deposit = DirectDeposit.create! valid_attributes
        put :update, {:id => direct_deposit.to_param, :direct_deposit => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested direct_deposit" do
      direct_deposit = DirectDeposit.create! valid_attributes
      expect {
        delete :destroy, {:id => direct_deposit.to_param}, valid_session
      }.to change(DirectDeposit, :count).by(-1)
    end

    it "redirects to the direct_deposits list" do
      direct_deposit = DirectDeposit.create! valid_attributes
      delete :destroy, {:id => direct_deposit.to_param}, valid_session
      expect(response).to redirect_to(direct_deposits_url)
    end
  end

end
